# Generated by Django 5.2.5 on 2026-02-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0002_category_ingredient_recipe_comment_recipeingredient_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="Untitled Recipe", max_length=200),
        ),
    ]
